environment:
  access_token:
    secure:ESG3buBaoWKVM85+BE6rd6NcBcn/Zvam6C2YFkOycad0IVQE7zUgrDNoFJamuKw9

install:
  - ps: Write-Host "Install R..."
  - choco install R
  - ps: Write-Host "R is installed."
  
  - ps: Write-Host "Install pandoc..."
  - choco install pandoc
  - ps: Write-Host "pandoc is installed"
  
#  - ps: Write-Host "Install rmarkdown..."
#  - ps: & "C:\Program Files\R\R-3.6.1\bin\rscript.exe" -e "install.packages('rmarkdown', repos='http://cran.case.edu/')"
#  - ps: Write-Host "rmarkdown is installed"
  
#  - ps: Write-Host "Install bookdown..."
#  - ps: & "C:\Program Files\R\R-3.6.1\bin\rscript.exe" -e "install.packages('bookdown', repos='http://cran.case.edu/')"
#  - ps: Write-Host "bookdown is installed"
 
#  - ps: Write-Host "Install reticulate..."
#  - ps: & "C:\\Program Files\\R\\R-3.6.1\\bin\\rscript.exe" -e "install.packages('reticulate', repos='http://cran.case.edu/')"
#  - ps: Write-Host "reticulate is installed"  
 
build_script:
  - ps: .\build.ps1
 
deploy_script:
  - git config --global credential.helper store
  - git config --global user.email "jinjie_liu@fas.harvard.edu" $env:op_build_user_email
  - git config --global user.name "liujinjie111" $env:op_build_user
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
#  - git subtree push --prefix docs origin gh-pages
#  - git add docs/*
#  - git commit -m "publish new book"
#  - git push origin head:master
  - git checkout -b gh-pages
#  - git rm *.html -rf
  - git rm *.json -rf
  - git rm template.gitignore
  - git rm .\images\* -rf 
  - git rm .\docs\* -rf
  - git checkout master .gitignore 
  - git checkout master docs
  - call xcopy .\docs .\ /E
  - touch .nojekyll
  - git add .
  - git commit
  - git push origin gh-pages
  - git checkout master